# Generated by Django 3.2.20 on 2023-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_friend_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_friend_chat',
            field=models.BooleanField(default=False),
        ),
    ]
