# Generated by Django 3.2.20 on 2023-10-30 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='related_friends',
        ),
        migrations.AddField(
            model_name='friendship',
            name='related_friends',
            field=models.ManyToManyField(related_name='related_friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
