# Generated by Django 3.2.20 on 2023-10-31 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20231030_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='private',
            old_name='contend',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='is_friend_chat',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.friend'),
        ),
        migrations.AlterField(
            model_name='private',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.friend'),
        ),
    ]
