# Generated by Django 3.2.20 on 2023-10-31 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20231031_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friends',
            new_name='user',
        ),
    ]
