# Generated by Django 3.2.20 on 2023-11-02 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0017_auto_20231101_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='related_friends',
            field=models.ManyToManyField(related_name='related_friendships', to=settings.AUTH_USER_MODEL),
        ),
    ]
