# Generated by Django 3.2.20 on 2023-11-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='is_accepted',
        ),
    ]
