# Generated by Django 3.2.20 on 2023-12-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_privatechat_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='is_read',
            new_name='is_read_sender',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='is_read_friend',
            field=models.BooleanField(default=False),
        ),
    ]
