# Generated by Django 3.2.20 on 2023-12-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_auto_20231210_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='is_read_sender',
            new_name='is_read',
        ),
    ]
