# Generated by Django 3.2.20 on 2023-12-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_rename_is_read_sender_privatechat_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatechat',
            old_name='is_read',
            new_name='is_read_sender',
        ),
    ]
