# Generated by Django 3.2.20 on 2023-12-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_auto_20231213_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatCount',
        ),
    ]
