# Generated by Django 3.2.20 on 2023-12-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_delete_chatcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
